renpy/vscode-language-renpy

Contributing.md

I noticed there was a help wanted involving a reference to a contributing.md. Here you go.

Provide a quality contributing.md

---

.github/workflows/codeql-analysis.yml
.github/workflows/publish.yml
README.md
package.json

- Automate deployment
- Adds extensions to Open VSX
- Adds CodeQL workflow

Config GitHub actions for automate deployment

---

README.md
package-lock.json
package.json

- Migrate from `vscode` to `vscode-test`.
- Upgrade packages.

Fix npm errors and migrate to vscode-test

---

CHANGELOG.md
src/diagnostics.ts

* Fix undefined store warnings for Classes and Callables [#56]

Ignore undefined warnings for Classes and Callables

---

CHANGELOG.md
package.json
src/navigationdata.ts
src/semantics.ts

* Fix semantic exception when position is negative [#62]
* Fix (Uncompiled Game) status bar text when editing a non-Renpy workspace/file

Fix semantic exception and status bar text

---

CHANGELOG.md
Visual Studio Code.edit.py

fix: Visual Studio Code.edit.py open files with spaces in the path

---

.github/dependabot.yml
.github/workflows/publish.yml

- Now the extension is only compiled once
- Create new draft release after publish
- Update node version
- Tweak dependabot updates

Update publishing workflow

---

CHANGELOG.md
README.md
package.json

Update README.md and prepare v2.0.7 release

---

examples/game/script.rpy
package.json
syntaxes/renpy.tmLanguage_2.json

* Added some test cases to make sure all variants are highlighted properly
* Added embedded meta tags to make sure the core tag is changed from code.renpy to code.python
* Merge styles into blocks to make it easier to reference later
* Improved python block captures and include all possible cases
* Add the label statement

Improved block capture and keywords

---

examples/.vscode/settings.json
src/extension.ts
syntaxes/renpy.tmLanguage_2.json

* Added back escaped chars, placeholders and tags from previous version.
* Improved meta information
* Added special cases for styled tags

New feature: styled strings

---

src/tokenizer/debug-decorator.ts
src/tokenizer/renpy.tokens.ts
src/tokenizer/token-patterns.ts
syntaxes/renpy.tmLanguage_2.json

* Adds meta data for menus and menu options
~~TODO:~~

New feature: menu statement

---

syntaxes/renpy.tmLanguage.json

Adds say statement support:
+ Character reference highlights
+ Meta tags around image arguments
+ Meta tags around character reference and strings
+ Special case for narrator statements

New feature: Say statements

---

language-configuration.json
package.json
snippets/snippets.json
syntaxes/renpy.python.tmLanguage.json
syntaxes/renpy.tmLanguage.json

Should be in functional state now

New feature: ATL support

---

.github/actions/setup/action.yml
.github/workflows/codeql-analysis.yml
.github/workflows/pr-check.yml
package-lock.json
package.json

- Run lint
- Build extension
Close #133

Adds basic PR validation

---

src/color.ts
src/extension.ts

According to the documentation, the function should return a `Thenable`. This updates the code to use that.

Possible fix for the color provider

---

.vscode/settings.json
examples/.vscode/settings.json
src/extension.ts

I finally had time to fix this 😄 
Fixes #172

fix: don't overwrite existing 'files.exclude'

---

package.json

[Fix] enables the extension when the language is renpy

---

src/color.ts
src/tokenizer/atl-token-patterns.ts
src/tokenizer/common-token-patterns.ts
src/tokenizer/debug-decorator.ts
src/tokenizer/python-token-patterns.ts
src/tokenizer/renpy-tokens.ts
src/tokenizer/token-definitions.ts
src/tokenizer/token-pattern-types.ts
src/tokenizer/token-patterns.ts
src/tokenizer/tokenizer.ts
syntaxes/renpy.tmLanguage.json

Extracted them from the json syntax grammar file
Added a whole bunch of new token types (some that might be removed later) Updated the tokenizer to fix some bugs
Added pattern stubs for all python patterns used by renpy patterns Added a debug name string temporarily for all base patterns

Update the tokenizer patterns

---

src/tokenizer/common-token-patterns.ts
src/tokenizer/debug-decorator.ts
src/tokenizer/renpy-tokens.ts
src/tokenizer/token-patterns.ts
src/tokenizer/tokenizer.ts
syntaxes/renpy.tmLanguage.json

- Add init offset statment
- Split number patterns into named repo
- Fix some tokenizer bugs
- Remove empty name matches

Syntax updates

---

src/navigationdata.ts
tsconfig.json

Fix missing JSON files in extension package

---

src/color.ts

@LuqueDaniel I wrote this code on my phone with GitHub codespaces, so I couldn't test this. Also the nodejs 'util' module still requires an import.
So if you can, please check if it works. I'd do it myself, but I won't be near my pc for the following week. 🙃
Also, I want to add another custom container 'HashSet' for this. That'll be a much more efficient way to perform this action. But for now this will suffice

Draft: First check if a key already exists

---

examples/unit_test.rpy
package.json
src/utilities/vector.ts
syntaxes/renpy.tmLanguage.json

If the ':' is not found, assume the python line ends at the end of a line

Fix over extended python line

---

.github/actions/setup/action.yml
.github/workflows/codeql-analysis.yml
.github/workflows/pr-check.yml
package-lock.json
package.json

Adds PR Check to master

---

package-lock.json
package.json

- Remove duplicate `vsce` dependency.
- Bump version to 2.2.0

Release 2.2.0

---

.eslintrc.json
.vscode/launch.json
TODO.md
package.json
src/color.ts
src/completion.ts
src/configuration.ts
src/definition.ts
src/diagnostics.ts
src/displayable.ts
src/extension.ts
src/hover.ts
src/logger.ts
src/outline.ts
src/references.ts
src/semantics.ts
src/signature.ts
src/tokenizer/debug-decorator.ts
src/tokenizer/tokenizer.ts
src/utilities/utils.ts

Will hopefully fix most issues with the development build
Also fixes #293

Fix infinite tokenizer loop

---

src/navigation-data.ts

wip, but I guess it's something

Assign proper types and deprecation tags

---

scripts/documentation/README.md
scripts/documentation/makeJson.py
scripts/documentation/makeJsonDoc.rpy

They might no longer work. Didn't have time to test these properly

Upload docs generator scripts

---

.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
examples/.vscode/settings.json
language-configuration.json
package-lock.json
package.json
snippets/snippets.json
syntaxes/log.injection.json
syntaxes/old.renpy.tmLanguage.json
syntaxes/renpy.atl.tmLanguage.json
syntaxes/renpy.python.tmLanguage.json
syntaxes/renpy.screen.tmLanguage.json
syntaxes/renpy.tmLanguage.json

Changed to use the build in formatter
Updated all json files to new formatting

Prettier formatting on json files was annoying me

---

examples/unit_test.rpy
syntaxes/renpy.tmLanguage.json

\+ Simplify narrator say statement

Fix missing highlights on string tags

---

src/utilities/functions.ts
src/utilities/hashset.ts
src/utilities/stack.ts
src/utilities/utils.ts
src/utilities/vector.ts
src/workspace.ts

This pull request adds comprehensive JSDoc comments and usage examples throughout the `Stack`, `Vector`, `HashSet`, `ValueEqualsSet` and utility functions to improve documentation and developer experience. The changes clarify the purpose, usage, and expected behavior of each, making the code easier to understand and maintain.
[View all changes](https://github.com/renpy/vscode-language-renpy/compare/481bce7~1..1c8ce1c)
- [`481bce7`](https://github.com/renpy/vscode-language-renpy/pull/501/commits/481bce75e1a64dd2ed962db3673e5c7a673c5873 "View commit \"481bce7\" details") docs: added rich docs to `Stack` class
- [`ac43c24`](https://github.com/renpy/vscode-language-renpy/pull/501/commits/ac43c2489d9a368c4a8a1198f6510a2f0d81dbd1 "View commit \"ac43c24\" details") docs: added rich docs to …

Improve JSDoc in Stack, Vector, HashSet, ValueEqualsSet and utility functions.
