renpy/vscode-language-renpy

CHANGELOG.md
src/extension.ts
src/semantics.ts

Fix syntax highlighting for self/cls so they are tokenized as keywords [#47] 
In the Dark theme, they appear as dark blue now. In Dark+ they appear as purple.

Fix syntax highlighting for self/cls so they are tokenized as keywords

---

package.json

Since new projects are untrusted by default, this extension needs to be able to run in untrusted workspaces, or it won't be applied to Ren'Py files by default.
I don't think there's much of a downside to this, and it should improve the out of the box experience with a fresh Ren'Py install.

Allow language-renpy to run in an untrusted workspace.

---

src/color.ts
src/completion.ts
src/extension.ts
src/hover.ts
src/navigation.ts
src/navigationdata.ts
src/outline.ts
src/semantics.ts
src/workspace.ts

Previously, both `substr` and `substring` methods were used interchangeably. From what I've tested both methods work the same and return the same result. Since `substr` is deprecated I've replaced it with `substring`.

Replace deprecated `substr` method with `substring`

---

CHANGELOG.md
src/semantics.ts

Now detect these keywords if there are spaces before and/or after the parenthesis.

Improves detection of `label`, `transform`, `screen`, `def` and `class` 

---

language-configuration.json
src/extension.ts
syntaxes/renpy.tmLanguage_2.json

* Store should be allowed to have single character names
* Allow multiple (tabs and) spaces between words
* Make sure we catch all characters between 'python' and ':'
* Don't use meta.embedded for the arguments since this will change the language and prevent indent
* Moved them to the language config to keep them where they belong
* Removed python keywords that are not available in Renpy code
* Split rules to get a more clear overview
* Special case for when in menu's

Small fixes in python block and new indenting rules

---

CHANGELOG.md
src/diagnostics.ts

* rxVariableCheck now allows the use of underscore in the name
* Added rxReservedVariableCheck that specifically tests for single underscore
* Added checkReservedRenpyNames function that pushes a warning if a single underscore variable was found
* Changed checkReservedPythonNames to result in a warning as the config suggests 'if (config.warnOnReservedVariableNames)'

fix: Allow double underscore in variable names

---

CHANGELOG.md
package.json
src/diagnostics.ts

From 4504e62 and 32409ed
* rxVariableCheck now allows the use of underscore in the name
* Added rxReservedVariableCheck that specifically tests for single
underscore
* Added checkReservedRenpyNames function that pushes a warning if a
single underscore variable was found
* Changed checkReservedPythonNames to result in a warning as the config
suggests 'if (config.warnOnReservedVariableNames)'
* Update CHANGELOG.md

reg: version 2.0.10 changes

---

.vscode/settings.json
src/tokenizer/token-patterns.ts
syntaxes/renpy.tmLanguage_2.json

+ Added the pause statement with number verification
* Fixed bracket mismatch in string placeholders
* Included the old version of:
- image
- transform
- style
- use
- screen
- keywords
I think this should bring this branch on par with the master branch.
_With the exception of illegal function/variable names_

Port back old Ren'Py statements + pause statement

---

language-configuration.json
syntaxes/renpy.tmLanguage.json

+ Labels now check for existing and invalid names
+ Call and jump now support from and pass statements
* Modified to code to be more modular
* Fixed some \t uses where \\t should be used

Improved patterns (label, call and jump)

---

.github/workflows/publish.yml
Contributing.md
package.json

* Updated GitHub actions to the latest major version.
* Now the releases will be published first in Visual Studio Marketplace because Open VSX doesn't support pre-releases.
* If the git tag ends in `pre-release`: a pre-release version will be published on Visual Studio Marketplace, it will not be published on Open VSX, and the release created on GitHub will be pre-release.
* Updated `Contributing.md` to explain versioning.

Updates publish workflow to support pre-releases

---

.vscode/settings.json
package.json
src/diagnostics.ts

As the flagged variable name is not valid for Ren'Py. If the `warnOnInvalidVariableNames` config is enabled it will be displayed as an error.
Closes #124

Change `warnOnInvalidVariableNames` config to boolean

---

syntaxes/renpy.tmLanguage.json

This fixes #182 as well as adds missing patterns to the statement. I checked the source code, renpy allows to use all `show` statement parameters with `scene`, like `as`, `onlayer`, etc. That means the code for `show` and `scene` is basically the same, so maybe you can find a way to reuse some bits, but maybe it's best to keep them separate in case renpy changes how it handles `scene`.

Fix scene statement highlighting

---

src/extension.ts

If `renpy.excludeCompiledFilesFromWorkspace` option isn't enabled, it doesn't call `excludeCompiledFilesConfig` function. Keeps the order of previously existing items in `files.exclude`. Only adds the patterns of the files generated by Ren'Py that aren't in the current `file.exclude`.
Fix #195

Fix excludeCompiledFilesFromWorkspace option

---

examples/unit_test.rpy
src/tokenizer/debug-decorator.ts
src/tokenizer/renpy-tokens.ts
src/tokenizer/token-patterns.ts
syntaxes/renpy.python.tmLanguage.json
syntaxes/renpy.tmLanguage.json

* Allow renpy string tags to be displayed in 'normal' python strings
* Adds a (minimal) implementation of the screen languague. (Currently it's mainly for the purpose of keeping screen languague syntax seperate)

Basic screen lang

---

src/decorator.ts

!== 0 would always be true now. Let's change it to check if the number of rules has changed, and only update if they are different

Fix incorrect check

---

src/diagnostics.ts

Prevents a 000*.rpy file from the Renpy SDK from being highlighted in red with the error message ```Filenames must begin with a letter or number, but may not begin with '00' as Ren'Py uses such files for its own purposes.```. A file is determined to be part of the sdk if it is under "renpy/common". 
Closes #283

Chore: Allow 000*.rpy files in renpy/common

---

package.json
src/extension.ts
src/workspace.ts

I don't have any expereince with typescript, so it may be a bit of a botched job, and I can't seem to get node.js to run on my machine, but this should be able to deal with https://github.com/LuqueDaniel/vscode-language-renpy/issues/115#issue-1239736338. I used a child process to run terminal command similar to what is done to watch for renpy compile data, but it should spawn a new renpy process in a new window.

RunRenpyViaplugin

---

package.json
src/extension.ts

It cleans up a few minor misspellings and properly adds a command to move all compiled files that don't have source files to the old-game directory. The command heading is "renpy.migrateOldFiles" and the formal title is "Cleanup unused compiled Ren'Py source files" 
Closes #144

Chore(Enhancement) - Add a command that cleans up compiled files.

---

.github/workflows/pr-check.yml
examples/test_ren.py
package.json
syntaxes/injection.json

Add injection grammar for renpy comments in _ren.py files
For now this will only work in doc strings, python syntax highlighting isn't changed

Support syntax highlighting in _ren.py files

---

src/signature.ts

openParenthesis could be -1 when this is triggered while removing the parens

Fix crash on function signature help

---

examples/unit_test.rpy
syntaxes/renpy.atl.tmLanguage.json
syntaxes/renpy.python.tmLanguage.json
syntaxes/renpy.screen.tmLanguage.json
syntaxes/renpy.style.tmLanguage.json
syntaxes/renpy.tmLanguage.json

* Added a whole bunch of missing style/screen properties/keywords
* Added missing layeredimage statement
* Added missing translate statement
* Fixed say argument highlighting
* Changed the token types of some
* Updated some tokens that used to be keywords to control flow. (I think it makes more sense like this, but feedback is welcome)
I should start updating the screen and style patterns to make use of ALT when it needs to. Many of the patterns and keyword are duplicated right now and I'm quite sure some blocks just allow ATL

Improved syntax highlighting

---

README.md

It seems the hidden instructions can be difficult to find.

Include clear build instructions on the front page

---

examples/unit_test.rpy
syntaxes/renpy.tmLanguage.json

Several keyword were not correctly handled because they needed a space before them. So they were not correctly highlighted when they were at the start of a line.
Also python code on a one-line '$' wasn't correctly working when written as follows: "$test = True"

Fixed unnecessary spaces before some commands or after '$' (one-line python)

---

.gitignore
src/debugger.ts
src/extension.ts

Was originally created to fix #388 and #390
But it looks like those issues were fixed and the problems just persisted in the debugger.
This PR makes use of that work in the debugger as well
It also looks like the `run` command was broken for the example project, because it expected the top level directory to end in `/game`, which isn't a requirement for the Ren'Py executable.
Removed the check and it works fine on the top level

Develop Use a child process for debugging instead of a terminal #478 

---

.github/actions/setup/action.yml
.github/workflows/codeql-analysis.yml
.github/workflows/pr-check.yml
.github/workflows/publish.yml
.husky/pre-commit
.prettierignore
.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
package-lock.json
package.json

This pull request updates and improves the project's GitHub Actions workflows, VS Code configuration, and recommended extensions. The main focus is on modernizing CI/CD workflows, improving developer experience in VS Code, and ensuring consistency in formatting and linting.
[View all changes](https://github.com/renpy/vscode-language-renpy/compare/0d111cb~1..fd29e74)
- [`0d111cb`](https://github.com/renpy/vscode-language-renpy/pull/501/commits/0d111cb0c3cb21a9f22ec49afa629b3544c1e292 "View commit \"0d111cb\" details") feat(husky): install `husky` and `lint-staged`
- [`2ab31d3`](https://github.com/renpy/vscode-language-renpy/pull/501/commits/2ab31d3480aa4499c32e18f609c95dadec83ec65 "View commit \"2ab31d3\" details") feat(husky): add `lint-staged` config and `npm prepare` script
- …

Workflow and config improvements

---

.husky/pre-commit
package.json

This pull request updates the pre-commit workflow to use a custom npm script instead of calling `lint-staged` directly. 
[View all changes](https://github.com/renpy/vscode-language-renpy/compare/afb665f~1..6423864)
- [`afb665f`](https://github.com/renpy/vscode-language-renpy/pull/512/commits/afb665f499eca4935046f2c33e8f3f6dea9877e3 "View commit \"afb665f\" details") chore: fix `prepare` script for husky v9
- [`6423864`](https://github.com/renpy/vscode-language-renpy/pull/512/commits/64238648a8144b75f8fcc2c0b2a57fb808d28475 "View commit \"6423864\" details") fix: add `precommit` npm task to improve compatibility
Fixes #511.

fix: add precommit npm task to improve compatibility
